'use strict';

import { expect } from 'chai';
import { TypeGraphImpl } from '../src/graph';
import { TypesGenerator } from '../src/generator';
import { TypeNode } from '../src/types';

describe('TypesGenerator', () => {
	let graph: TypeGraphImpl;
	let generator: TypesGenerator;

	beforeEach(() => {
		graph = new TypeGraphImpl();
		generator = new TypesGenerator(graph);
	});

	describe('basic generation', () => {
		it('should generate header with comments', () => {
			const result = generator.generate();

			expect(result.content).to.include('Generated by @mnemonica/tactica');
			expect(result.content).to.include('DO NOT EDIT');
		});

		it('should generate module declaration', () => {
			const node = TypeGraphImpl.createNode('FirstType', undefined, 'test.ts', 1, 1);
			graph.addRoot(node);

			const result = generator.generate();

			expect(result.content).to.include('declare module "mnemonica"');
			expect(result.content).to.include('FirstTypeInstance');
		});

		it('should generate instance interface', () => {
			const node = TypeGraphImpl.createNode('FirstType', undefined, 'test.ts', 1, 1);
			graph.addRoot(node);

			const result = generator.generate();

			expect(result.content).to.include('interface FirstTypeInstance');
		});
	});

	describe('nested types', () => {
		it('should generate nested constructor properties', () => {
			const parent = TypeGraphImpl.createNode('Parent', undefined, 'test.ts', 1, 1);
			const child = TypeGraphImpl.createNode('Child', parent, 'test.ts', 5, 1);
			
			graph.addRoot(parent);
			graph.addChild(parent, child);

			const result = generator.generate();

			expect(result.content).to.include('ParentInstance');
			expect(result.content).to.include('Child:');
			expect(result.content).to.include('new (...args: unknown[]): ChildInstance');
		});

		it('should include parent in extends clause', () => {
			const parent = TypeGraphImpl.createNode('Parent', undefined, 'test.ts', 1, 1);
			const child = TypeGraphImpl.createNode('Child', parent, 'test.ts', 5, 1);
			
			graph.addRoot(parent);
			graph.addChild(parent, child);

			const result = generator.generate();

			expect(result.content).to.include('ChildInstance extends ParentInstance');
		});
	});

	describe('properties', () => {
		it('should return types array', () => {
			const node = TypeGraphImpl.createNode('User', undefined, 'test.ts', 1, 1);
			node.properties.set('name', { name: 'name', type: 'string', optional: false });
			graph.addRoot(node);

			const result = generator.generate();

			expect(result.types).to.include('UserInstance');
		});
	});
});
