'use strict';

import { expect } from 'chai';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import * as ts from 'typescript';
import { TypeGraphImpl } from '../src/graph';
import { TypesGenerator } from '../src/generator';

describe('TypesGenerator', () => {
	let graph: TypeGraphImpl;
	let generator: TypesGenerator;

	beforeEach(() => {
		graph = new TypeGraphImpl();
		generator = new TypesGenerator(graph);
	});

	describe('generateTypesFile', () => {
		it('should generate header with comments', () => {
			const result = generator.generateTypesFile();

			expect(result.content).to.include('Generated by @mnemonica/tactica');
			expect(result.content).to.include('DO NOT EDIT');
		});

		it('should generate type alias exports', () => {
			const node = TypeGraphImpl.createNode('FirstType', undefined, 'test.ts', 1, 1);
			graph.addRoot(node);

			const result = generator.generateTypesFile();

			expect(result.content).to.include('export type FirstType');
		});

		it('should return types array', () => {
			const node = TypeGraphImpl.createNode('User', undefined, 'test.ts', 1, 1);
			node.properties.set('name', { name : 'name', type : 'string', optional : false });
			graph.addRoot(node);

			const result = generator.generateTypesFile();

			expect(result.types).to.include('User');
		});
	});

	describe('generateGlobalAugmentation', () => {
		it('should generate global declaration', () => {
			const node = TypeGraphImpl.createNode('FirstType', undefined, 'test.ts', 1, 1);
			graph.addRoot(node);

			const result = generator.generateGlobalAugmentation();

			expect(result.content).to.include('declare global');
			expect(result.content).to.include('FirstType');
		});

		it('should generate instance type alias', () => {
			const node = TypeGraphImpl.createNode('FirstType', undefined, 'test.ts', 1, 1);
			graph.addRoot(node);

			const result = generator.generateGlobalAugmentation();

			// root types are declared as interfaces (declaration merging with
			// @decorate classes); a same-named `type` alias would be TS2300
			expect(result.content).to.include('interface FirstType');
			expect(result.content).to.not.include('type FirstType =');
		});

		it('should generate nested constructor properties', () => {
			const parent = TypeGraphImpl.createNode('Parent', undefined, 'test.ts', 1, 1);
			const child = TypeGraphImpl.createNode('Child', parent, 'test.ts', 5, 1);
			
			graph.addRoot(parent);
			graph.addChild(parent, child);

			const result = generator.generateGlobalAugmentation();

			expect(result.content).to.include('Parent');
			expect(result.content).to.include('Child:');
			expect(result.content).to.include('new () => Parent_Child');
		});

		it('should include parent in intersection type', () => {
			const parent = TypeGraphImpl.createNode('Parent', undefined, 'test.ts', 1, 1);
			const child = TypeGraphImpl.createNode('Child', parent, 'test.ts', 5, 1);

			graph.addRoot(parent);
			graph.addChild(parent, child);

			const result = generator.generateGlobalAugmentation();

			expect(result.content).to.include('Child = ProtoFlat<Parent,');
		});

		it('should emit a global file that compiles without TS2300', () => {
			const root = TypeGraphImpl.createNode('UserType', undefined, 'repro.ts', 1, 1);
			root.properties.set('name', { name : 'name', type : 'string', optional : false });
			graph.addRoot(root);
			const child = TypeGraphImpl.createNode('AdminType', root, 'repro.ts', 5, 1);
			child.properties.set('role', { name : 'role', type : 'string', optional : false });
			graph.addChild(root, child);

			const { content } = generator.generateGlobalAugmentation();

			// compile the generated file for real — string-inclusion tests
			// missed the root alias vs class interface collision (TS2300)
			const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tactica-global-'));
			const filePath = path.join(tmpDir, 'index.d.ts');
			fs.writeFileSync(filePath, content);

			const mnemonicaTypes = path.join(__dirname, '..', 'node_modules', 'mnemonica', 'build', 'index.d.ts');
			const program = ts.createProgram([ filePath ], {
				strict           : true,
				noEmit           : true,
				target           : ts.ScriptTarget.ES2020,
				module           : ts.ModuleKind.ES2020,
				moduleResolution : ts.ModuleResolutionKind.Bundler,
				baseUrl          : tmpDir,
				paths            : { mnemonica : [ mnemonicaTypes ] },
			});
			const diagnostics = ts.getPreEmitDiagnostics(program);
			const errors = diagnostics
				.filter(d => d.category === ts.DiagnosticCategory.Error)
				.map(d => `TS${d.code}: ${ts.flattenDiagnosticMessageText(d.messageText, ' ')}`);

			expect(errors).to.deep.equal([]);
		});
	});

	describe('generateTypeRegistry', () => {
		it('should generate module augmentation for mnemonica TypeRegistry', () => {
			const node = TypeGraphImpl.createNode('UserType', undefined, 'test.ts', 1, 1);
			node.properties.set('name', { name : 'name', type : 'string', optional : false });
			graph.addRoot(node);

			const result = generator.generateTypeRegistry();

			expect(result.content).to.include('declare module \'mnemonica\'');
			expect(result.content).to.include('interface TypeRegistry');
			expect(result.content).to.include('\'UserType\':');
		});

		it('should include import for instance types', () => {
			const node = TypeGraphImpl.createNode('UserType', undefined, 'test.ts', 1, 1);
			graph.addRoot(node);

			const result = generator.generateTypeRegistry();

			expect(result.content).to.include('import type {');
			expect(result.content).to.include('UserType,');
		});

		it('should re-export TypeRegistry for backward compatibility', () => {
			const node = TypeGraphImpl.createNode('UserType', undefined, 'test.ts', 1, 1);
			graph.addRoot(node);

			const result = generator.generateTypeRegistry();

			expect(result.content).to.include('import type { TypeRegistry } from \'mnemonica\'');
			expect(result.content).to.include('export type { TypeRegistry }');
		});

		it('should return generated type names', () => {
			const node = TypeGraphImpl.createNode('UserType', undefined, 'test.ts', 1, 1);
			graph.addRoot(node);

			const result = generator.generateTypeRegistry();

			expect(result.types).to.include('UserType');
		});

		it('should generate nested type entries', () => {
			const parent = TypeGraphImpl.createNode('UserType', undefined, 'test.ts', 1, 1);
			const child = TypeGraphImpl.createNode('AdminType', parent, 'test.ts', 5, 1);
			graph.addRoot(parent);
			graph.addChild(parent, child);

			const result = generator.generateTypeRegistry();

			expect(result.content).to.include('\'UserType\':');
			expect(result.content).to.include('\'UserType.AdminType\':');
		});
	});

	describe('generateSingleType', () => {
		it('should return type text for a single node', () => {
			const node = TypeGraphImpl.createNode('UserType', undefined, 'test.ts', 1, 1);
			node.properties.set('name', { name : 'name', type : 'string', optional : false });
			graph.addRoot(node);

			const result = generator.generateSingleType(node);

			expect(result).to.be.a('string');
			expect(result).to.include('UserType');
		});
	});

	describe('decorated-class constructor signatures', () => {
		it('should use constructorParams in registry for a class-like node', () => {
			const node = TypeGraphImpl.createNode('Order', undefined, 'test.ts', 1, 1);
			node.constructorParams = [
				{ name : 'data', type : '{ orderId: string; total: number }', optional : false }
			];
			graph.addRoot(node);

			const result = generator.generateTypeRegistry();

			expect(result.content).to.include('\'Order\': new (data: { orderId: string; total: number }) => Order');
		});

		it('should use constructorParams in types.ts for a nested class-like node', () => {
			const parent = TypeGraphImpl.createNode('Order', undefined, 'test.ts', 1, 1);
			const child = TypeGraphImpl.createNode('LineItem', parent, 'test.ts', 5, 1);
			child.constructorParams = [
				{ name : 'data', type : '{ sku: string; qty: number }', optional : false }
			];
			graph.addRoot(parent);
			graph.addChild(parent, child);

			const result = generator.generateTypesFile();

			expect(result.content).to.include('LineItem: new (data: { sku: string; qty: number }) => Order_LineItem');
		});
	});

	describe('ESM mode', () => {
		it('should append .js extension to imports in ESM mode', () => {
			const esmGenerator = new TypesGenerator(graph, true);
			const node = TypeGraphImpl.createNode('UserType', undefined, 'test.ts', 1, 1);
			graph.addRoot(node);

			const result = esmGenerator.generateTypeRegistry();

			expect(result.content).to.include('from \'./types.js\'');
		});

		it('should not append .js extension in default mode', () => {
			const node = TypeGraphImpl.createNode('UserType', undefined, 'test.ts', 1, 1);
			graph.addRoot(node);

			const result = generator.generateTypeRegistry();

			expect(result.content).to.include('from \'./types\'');
			expect(result.content).to.not.include('from \'./types.js\'');
		});
	});
});
