'use strict';

import { TypeNode, GeneratedTypes } from './types';
import { TypeGraphImpl } from './graph';

/**
 * TypeScript declaration file generator
 */
export class TypesGenerator {
	constructor(private graph: TypeGraphImpl) {}

	/**
		* Generate global augmentation file that augments user classes directly
		* This allows using decorated classes without manual type casting
		*
		* All types are placed in the global scope via declare global, which allows
		* them to be accessed from any module without imports. Interfaces declared
		* in the global scope will merge with classes of the same name in user modules.
		*/
	generateGlobalAugmentation(): GeneratedTypes {
		const lines: string[] = [];
		const generatedTypes: string[] = [];

		// Header - make this a module so we can use declare global
		lines.push('// Generated by @mnemonica/tactica - DO NOT EDIT');
		lines.push('// This file provides automatic type augmentation for decorated classes');
		lines.push('');
		lines.push('/* eslint-disable @typescript-eslint/no-empty-object-type */');
		lines.push('/* eslint-disable @typescript-eslint/no-empty-interface */');
		lines.push('');

		// Import ProtoFlat and TypeConstructor from mnemonica
		lines.push("import type { ProtoFlat, TypeConstructor } from 'mnemonica';");
		lines.push('');

		// Make this a module so we can use declare global
		lines.push('export {};');
		lines.push('');

		// All types go inside declare global so they are globally accessible
		lines.push('declare global {');
		lines.push('');


		// Generate instance types for all types - in global scope
		for (const root of this.graph.roots.values()) {
			for (const node of this.graph.dfs(root)) {
				const instanceName = this.getInstanceTypeName(node);
				generatedTypes.push(instanceName);
				this.generateInstanceType(node, lines, 1);
			}
		}

		// Generate class interfaces - in global scope for declaration merging
		// These interfaces will merge with classes of the same name in user modules
		lines.push('	// Class interfaces for declaration merging');
		lines.push('	// These merge with @decorate() classes to provide proper typing');
		lines.push('');
		for (const root of this.graph.roots.values()) {
			for (const node of this.graph.dfs(root)) {
				this.generateClassInterface(node, lines, 1);
			}
		}

		lines.push('}');

		return {
			content: lines.join('\n'),
			types: generatedTypes,
		};
	}

	/**
		 * Generate instance type alias (describes what the instance IS)
		 * Uses ProtoFlat for proper inheritance (excludes overridden parent props)
		 */
	private generateInstanceType(node: TypeNode, lines: string[], indent: number): void {
		const indentStr = '\t'.repeat(indent);
		const instanceName = this.getInstanceTypeName(node);

		if (node.parent) {
			// Nested type: Use ProtoFlat to properly exclude overridden properties
			lines.push(`${indentStr}type ${instanceName} = ProtoFlat<${this.getInstanceTypeName(node.parent)}, {`);
		} else {
			// Root type: just the properties object
			lines.push(`${indentStr}type ${instanceName} = {`);
		}

		// Add instance properties
		for (const [propName, propInfo] of node.properties.entries()) {
			const optional = propInfo.optional ? '?' : '';
			const readonly = propInfo.readonly ? 'readonly ' : '';
			lines.push(`${indentStr}\t${readonly}${propName}${optional}: ${propInfo.type};`);
		}

		// Add nested constructor properties (only for root types)
		// Nested type constructors are accessible via parent, not directly on instances
		if (!node.parent) {
			for (const child of node.children.values()) {
				const childInstanceType = this.getInstanceTypeName(child);
				lines.push(`${indentStr}\t${child.name}: TypeConstructor<${childInstanceType}>;`);
			}
		}

		// For nested types, add Subtype: undefined to indicate no further subtypes
		// This is needed for strict chain behavior
		if (node.parent) {
			lines.push(`${indentStr}\t${node.name}: undefined;`);
		}

		// Close the type properly - ProtoFlat uses }>; for nested, }; for root
		if (node.parent) {
			lines.push(`${indentStr}}>;`);
		} else {
			lines.push(`${indentStr}};`);
		}

		// Add empty line after each type
		lines.push('');
	}

		/**
		 * Generate class interface for TypeScript declaration merging
		 * This merges with the actual class to provide proper typing
		 */
		private generateClassInterface(node: TypeNode, lines: string[], indent: number): void {
		const indentStr = '\t'.repeat(indent);

		// Build extends clause
			const extendsTypes: string[] = [];
			if (node.parent) {
				extendsTypes.push(node.parent.name);
			}

			const extendsClause = extendsTypes.length > 0
				? ` extends ${extendsTypes.join(', ')}`
				: '';

			// Interface with same name as class - TypeScript merges these
			lines.push(`${indentStr}interface ${node.name}${extendsClause} {`);
			
			// Add all instance properties (for type merging)
			for (const [propName, propInfo] of node.properties.entries()) {
				const optional = propInfo.optional ? '?' : '';
				const readonly = propInfo.readonly ? 'readonly ' : '';
				lines.push(`${indentStr}\t${readonly}${propName}${optional}: ${propInfo.type};`);
			}

			// Add subtype constructors (non-optional so they're accessible) - only for root types
				if (!node.parent) {
					for (const child of node.children.values()) {
						const childInstanceType = this.getInstanceTypeName(child);
						lines.push(`${indentStr}\t${child.name}: TypeConstructor<${childInstanceType}>;`);
					}
				}
	
				lines.push(`${indentStr}}`);
			lines.push('');
		}
		
			/**
		* Generate a types.ts file with complete instance interfaces
		* This includes all properties extracted from the constructors
		*/
	generateTypesFile(): GeneratedTypes {
		const lines: string[] = [];
		const generatedTypes: string[] = [];

		// Header
		lines.push('// Generated by @mnemonica/tactica - DO NOT EDIT');
		lines.push('// This file provides complete TypeScript interfaces for Mnemonica types');
		lines.push('');
		lines.push('/* eslint-disable @typescript-eslint/no-empty-object-type */');
		lines.push('/* eslint-disable @typescript-eslint/no-empty-interface */');
		lines.push('');

		// Import ProtoFlat and TypeConstructor from mnemonica
		lines.push("import type { ProtoFlat, TypeConstructor } from 'mnemonica';");
		lines.push('');

		// Generate complete instance interfaces
		for (const root of this.graph.roots.values()) {
			for (const node of this.graph.dfs(root)) {
				const interfaceName = this.getInstanceTypeName(node);
				generatedTypes.push(interfaceName);
				this.generateCompleteInstanceInterface(node, lines);
			}
		}

		return {
			content: lines.join('\n'),
			types: generatedTypes,
		};
	}

	/**
		 * Generate a complete instance type alias with all properties
		 * This is for the types.ts file that users import from
		 */
	private generateCompleteInstanceInterface(node: TypeNode, lines: string[]): void {
		const typeName = this.getInstanceTypeName(node);

		if (node.parent) {
			// Nested type: Use ProtoFlat to properly exclude overridden properties
			lines.push(`export type ${typeName} = ProtoFlat<${this.getInstanceTypeName(node.parent)}, {`);
		} else {
			// Root type: just the properties object
			lines.push(`export type ${typeName} = {`);
		}

		// Add instance properties extracted from the constructor
		for (const [propName, propInfo] of node.properties.entries()) {
			const optional = propInfo.optional ? '?' : '';
			const readonly = propInfo.readonly ? 'readonly ' : '';
			lines.push(`\t${readonly}${propName}${optional}: ${propInfo.type};`);
		}

		// Add nested constructor properties for non-leaf nodes
		// Leaf nodes (no children) don't get constructor properties
		// This follows mnemonica's strictChain behavior
		if (node.children.size > 0) {
			for (const child of node.children.values()) {
				const childInstanceType = this.getInstanceTypeName(child);
				lines.push(`\t${child.name}: TypeConstructor<${childInstanceType}>;`);
			}
		}

		// For nested types, add this node's constructor and all siblings from same parent as undefined
		// This is needed for strict chain behavior - parent undefineds are inherited via ProtoFlat
		if (node.parent) {
			// Add this node's own constructor as undefined
			lines.push(`\t${node.name}: undefined;`);

			// Add all siblings (other children of the same parent) as undefined
			for (const sibling of node.parent.children.values()) {
				if (sibling.name !== node.name) {
					lines.push(`\t${sibling.name}: undefined;`);
				}
			}
		}

		// Close the type properly - ProtoFlat uses }>; for nested, }; for root
		if (node.parent) {
			lines.push('}>;');
		} else {
			lines.push('};');
		}
		lines.push('');
	}

	/**
		 * Generate a simple type declaration for a single type
		 */
	generateSingleType(node: TypeNode): string {
		const lines: string[] = [];
		this.generateCompleteInstanceInterface(node, lines);
		return lines.join('\n');
	}

	/**
		 * Generate TypeRegistry interface for type-safe lookupTyped() function
		 * Import this interface and pass it to lookupTyped<TypeRegistry>() from mnemonica
		 */
	generateTypeRegistry(): GeneratedTypes {
		const lines: string[] = [];
		const generatedTypes: string[] = [];

		// Header
		lines.push('// Generated TypeRegistry for type-safe mnemonica.lookupTyped<TypeRegistry>()');
		lines.push('// Import this interface and use with lookupTyped from mnemonica');
		lines.push('//');
		lines.push('// Usage:');
		lines.push("//   import { lookupTyped } from 'mnemonica';");
		lines.push("//   import { TypeRegistry } from './.tactica/registry';");
		lines.push("//   const Sentience = lookupTyped<TypeRegistry>('Sentience');");
		lines.push('//   // TypeScript knows: Sentience is a constructor for SentienceInstance');
		lines.push("//   const instance = new Sentience({ purpose: 'AI' });");
		lines.push('//   // instance has full intellisense for Consciousness, Memory, etc.');
		lines.push('');

		// Import instance types from types.ts
		lines.push('import type {');
		for (const root of this.graph.roots.values()) {
			for (const node of this.graph.dfs(root)) {
				const instanceTypeName = this.getInstanceTypeName(node);
				lines.push(`\t${instanceTypeName},`);
				generatedTypes.push(instanceTypeName);
			}
		}
		lines.push('} from \'./types\';');
		lines.push('');

		// Generate module augmentation for mnemonica TypeRegistry
		lines.push('/**');
		lines.push(' * Type registry augmenting mnemonica\'s TypeRegistry interface');
		lines.push(' * This enables type-safe lookupTyped() without explicit type arguments');
		lines.push(' *');
		lines.push(' * Usage: const SomeType = lookupTyped(\'SomeType\'); // Fully typed!');
		lines.push(' */');
		lines.push('declare module \'mnemonica\' {');
		lines.push('	interface TypeRegistry {');

		// Generate entries for all type paths
		for (const root of this.graph.roots.values()) {
			for (const node of this.graph.dfs(root)) {
				const fullPath = this.getFullPath(node);
				const instanceType = this.getInstanceTypeName(node);
				// Generate typed constructor signature for nested types with properties
				const constructorSig = this.generateConstructorSignature(node);
				lines.push(`\t\t'${fullPath}': ${constructorSig} => ${instanceType};`);
			}
		}

		lines.push('\t}');
		lines.push('}');
		lines.push('');

		// Re-export for backward compatibility and explicit usage
		lines.push('import type { TypeRegistry } from \'mnemonica\';');
		lines.push('export type { TypeRegistry };');

		return {
			content: lines.join('\n'),
			types: generatedTypes,
		};
	}

	/**
		 * Generate constructor signature for a type node
		 * Uses constructorParams for TypeRegistry signature (not instance properties)
		 */
	private generateConstructorSignature(node: TypeNode): string {
		// Use constructorParams if available, otherwise fall back to empty signature
		const params = node.constructorParams;

		if (!params || params.size === 0) {
			return 'new (...args: unknown[])';
		}

		// Build typed constructor signature from constructor parameters
		const props: string[] = [];
		for (const [propName, propInfo] of params) {
			const optional = propInfo.optional ? '?' : '';
			props.push(`${propName}${optional}: ${propInfo.type}`);
		}

		// Return constructor signature with data parameter
		return `new (data: { ${props.join('; ')} })`;
	}

	/**
		 * Get the full dotted path for a type node
		 */
	private getFullPath(node: TypeNode): string {
		if (!node.parent) {
			return node.name;
		}
		return `${this.getFullPath(node.parent)}.${node.name}`;
	}

	/**
	 * Get the instance type name for a node
	 * Uses full path with underscores: Usages.UsageEntry -> Usages_UsageEntry
	 */
	private getInstanceTypeName(node: TypeNode): string {
		const fullPath = this.getFullPath(node);
		return fullPath.replace(/\./g, '_');
	}
}
